title: ""
email: safinramaz@mail.ru
description: >- # this means to ignore newlines until "baseurl:"
        "придумать что-то на это пустое место"
baseurl:  # the subpath of your site, e.g. /blog
url: "https://ramazsafin.github.io/portfolio/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  RamazSafin

# Build settings
theme: minima
plugins:
  - jekyll-feed

nav:
  - title: "Главная"
    url: /
  - title: "Обо мне"
    url: /about/
  - title: "Портфолио"
    url: /portfolio/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

